# Travis Configuration
# sudo: false
language: cpp
os:
  - osx
compiler:
  - clang
  - gcc

#####################################
# For Migration to Container Builds #
#####################################

# Install Container Dependencies
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - fglrx-dev # (TravisCI: #4228, apt-package-whitelist: #383)
#       - g++-4.8
#       - opencl-headers

# Install Coveralls (TravisCI: #3563)
# before_script:
#   - export PATH=$HOME/.local/bin:$PATH
#   - pip install cpp-coveralls --user `whoami`

########################################
# Delete This on Container Integration #
########################################

install:
  - if [ "$CXX" = "g++" ]; then export CXX=g++-4.8; fi
  - brew install cmake
  - pip install cpp-coveralls

########################################

# Run the Test Script
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make all
  - clinfo > /dev/null
  - make check

# Upload Code Coverage Data
after_success:
  - coveralls --exclude chlorine/include/cl.hpp  --exclude examples --exclude tests

# Display Compiler Information
after_script:
  - $CXX --version
