# Travis Configuration
language: cpp
script: make
compiler:
  - clang
  - gcc

# Install OpenCL Headers
before_install:
  - sudo apt-get update  -qq
  - sudo apt-get install -qq fglrx
  - sudo apt-get install -qq opencl-headers

  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then ln -s /usr/bin/g++-4.9 /usr/bin/g++; fi

after_script:
  - $CXX --version
