# Travis Configuration
sudo: false
language: cpp
script: make all && make test
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - fglrx=2:8.960-0ubuntu1
      - g++-4.8
      - opencl-headers

# Upload Code Coverage Data
after_success:
  - coveralls --exclude chlorine/cl.hpp  --exclude examples --exclude tests

# Display Compiler Information
after_script:
  - $CXX --version
