# Travis Configuration
sudo: false
language: cpp
compiler:
  - clang
  - gcc

# Install Container Dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - fglrx-dev # (TravisCI: #4228, apt-package-whitelist: #383)
      - g++-4.8
      - opencl-headers

# Install Coveralls (TravisCI: #3563)
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install cpp-coveralls --user `whoami`

# Run the Test Script
script:
  - make all
  - make check

# Upload Code Coverage Data
after_success:
  - coveralls --exclude chlorine/cl.hpp  --exclude examples --exclude tests

# Display Compiler Information
after_script:
  - $CXX --version
